In [2]:
import numpy as np

<h3>First example using numpy</h3>

In [4]:
a = np.arange(6).reshape(2,3)

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

<b>The dimensions of the array</b>

In [7]:
a.ndim

2

<b>The shape of the array</b>

In [9]:
a.shape

(2, 3)

In [10]:
a.dtype.name

'int64'

In [11]:
a.itemsize

8

In [12]:
type(a)

numpy.ndarray

<b>Create new array</b>

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a.ndim

2

In [18]:
b = np.array([1,2,3,4])

In [19]:
b.ndim

1

In [22]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

In [23]:
c.ndim

2

<b>Generate the zeros matrix</b>

In [24]:
zeros = np.zeros((3,4))

In [25]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<b>Generate the ones matrix</b>

In [37]:
ones = np.ones((3,4))

In [27]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
ran = np.arange(5)

In [34]:
ran

array([0, 1, 2, 3, 4])

<b>Find the sqrt of the elements</b>

In [35]:
np.sqrt(ran)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

<b>Find the exponent of the elements</b>

In [36]:
np.exp(ran)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

<b>Generate the powers of the elements</b>

In [38]:
ran**3

array([ 0,  1,  8, 27, 64])

<b>Generate a new array of powers of elements</b>

In [44]:
ran2 = np.arange(9)**2

In [45]:
ran2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

<b>Get a subset of the elements in the list - start at element 1 and go to the 3rd entry in the list</b>

In [46]:
ran2[1:3]

array([1, 4])

In [48]:
ran2[1:5]

array([ 1,  4,  9, 16])

In [50]:
ran2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [51]:
ran2[3:5]

array([ 9, 16])

In [52]:
ran2[0:5]

array([ 0,  1,  4,  9, 16])

<b>Loop over list</b>

In [53]:
for i in ran2:
    print(i)

0
1
4
9
16
25
36
49
64


<b>Build a function to generate an array</b>

In [57]:
def f(x,y):
    return 10*x+y

In [58]:
b = np.fromfunction(f,(5,6), dtype=int)

In [59]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

<b>Get 30 to 34 out of the matrix</b>

In [60]:
b[3]

array([30, 31, 32, 33, 34, 35])

In [65]:
b[3,0:5]

array([30, 31, 32, 33, 34])

<b>Get 32 to 35 out of the matrix</b>

In [66]:
b[3,2:6]

array([32, 33, 34, 35])

<b>Get 1 to 41 out of the matrix - start with 0 row and get the 1st column</b>

In [70]:
b[0:,1]

array([ 1, 11, 21, 31, 41])

<b>Another way is to go from rows 0-5 and get the 1st element</b>

In [72]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [76]:
for row in b:
    print("row = ",row)


row =  [0 1 2 3 4 5]
row =  [10 11 12 13 14 15]
row =  [20 21 22 23 24 25]
row =  [30 31 32 33 34 35]
row =  [40 41 42 43 44 45]


In [78]:
for col in np.transpose(b):
    print("col = ",col)

col =  [ 0 10 20 30 40]
col =  [ 1 11 21 31 41]
col =  [ 2 12 22 32 42]
col =  [ 3 13 23 33 43]
col =  [ 4 14 24 34 44]
col =  [ 5 15 25 35 45]


<b>Resize array</b>

In [81]:
np.size(b)

30

In [82]:
np.ndim(b)

2

In [86]:
np.vstack(b)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

In [87]:
np.hstack(b)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24,
       25, 30, 31, 32, 33, 34, 35, 40, 41, 42, 43, 44, 45])

<b>Stack arrays</b>

In [88]:
a=np.arange(1,5)

In [89]:
a

array([1, 2, 3, 4])

In [90]:
b=np.arange(6,10)

In [91]:
b

array([6, 7, 8, 9])

In [93]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

<b>Stack arrays horizontally</b>

In [94]:
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

<b>Create column vectors from rows</b>

In [95]:
from numpy import newaxis

In [96]:
a

array([1, 2, 3, 4])

In [99]:
a[:,newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [100]:
ran2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

<b>Split array into several</b>

In [101]:
np.hsplit(a,2)

[array([1, 2]), array([3, 4])]

In [102]:
c = np.hsplit(a,2)

In [103]:
c

[array([1, 2]), array([3, 4])]

In [108]:
c[0:1]

[array([1, 2])]

In [109]:
np.sum(c[0:1])

3

<b>Create a pointer to an array</b>

In [110]:
a

array([1, 2, 3, 4])

In [121]:
b=a

In [112]:
b

array([1, 2, 3, 4])

In [113]:
b is a

True

In [119]:
id(a)

4772951584

In [122]:
id(b)

4772951584

<b>Create a copy of an array</b>

In [129]:
d = a.view()

In [130]:
d is a

False

In [131]:
d

array([1, 2, 3, 4])

In [135]:
a[1]

2

In [136]:
a[1] = 5

In [137]:
d

array([1, 5, 3, 4])

<b>Create a deep copy of the elements</b>

In [138]:
d = a.copy()

In [139]:
d is a

False

In [140]:
d

array([1, 5, 3, 4])

In [141]:
a[1] = 2

In [142]:
a

array([1, 2, 3, 4])

In [143]:
d

array([1, 5, 3, 4])

In [144]:
my_dict = {a: [], b: [], c: []}

TypeError: unhashable type: 'numpy.ndarray'

In [145]:
import pandas as pd

In [147]:
my_dict = {'a': [], 'b': [], 'c': []}

In [148]:
my_dict

{'a': [], 'b': [], 'c': []}

In [149]:
dftest = pd.DataFrame(my_dict)

In [150]:
dftest

Empty DataFrame
Columns: [a, b, c]
Index: []

In [151]:
dftest.a

Series([], Name: a, dtype: float64)

In [152]:
dftest.a = [1,2,3]

In [153]:
dftest

a   b   c
0  1 NaN NaN
1  2 NaN NaN
2  3 NaN NaN

In [154]:
dftest.a

0    1
1    2
2    3
Name: a, dtype: int64

In [155]:
letters

NameError: name 'letters' is not defined

In [27]:
np.array([1,2,3])

array([1, 2, 3])

In [29]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array([range(i, i+2) for i in [2,4,6]])

array([[2, 3],
       [4, 5],
       [6, 7]])

In [6]:
np.array([range(i, i*2) for i in [2,4,6]])

array([range(2, 4), range(4, 8), range(6, 12)], dtype=object)

In [10]:
np.array([range(i, i+5) for i in [2,4,6]])

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.zeros(12, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(12, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.arange(0,5,2)

array([0, 2, 4])

In [18]:
np.full((2,2), 1.23)

array([[1.23, 1.23],
       [1.23, 1.23]])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.random.random((3,3))

array([[0.15620127, 0.48961434, 0.95419039],
       [0.84496397, 0.03708223, 0.5246233 ],
       [0.17987765, 0.71423494, 0.70961564]])

In [22]:
np.random.random((5,5))

array([[0.68566082, 0.52072312, 0.73871207, 0.15740499, 0.11014831],
       [0.07344541, 0.39135242, 0.24326605, 0.77480325, 0.89031809],
       [0.17482082, 0.36862387, 0.79184609, 0.54195987, 0.26994473],
       [0.70881251, 0.91834734, 0.27075219, 0.80588196, 0.10444567],
       [0.89170843, 0.08636069, 0.1702728 , 0.88089799, 0.64307275]])

In [23]:
np.random.normal(0, 1, (3,3))

array([[ 0.35099944, -0.89562342, -0.69239753],
       [ 0.56790298,  0.95827996,  0.64505455],
       [-0.26560415, -0.25560756, -1.24743622]])

In [24]:
np.random.randint(0, 10, (3,3))

array([[3, 4, 0],
       [5, 1, 0],
       [6, 1, 5]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.empty(3)

array([4.36002168e-114, 6.32672818e+180, 4.74483502e+170])